import type { Metadata } from "next";
import { Orbitron } from "next/font/google";
import localFont from "next/font/local";
import PrimaryNav from "../components/layouts/PrimaryNav";
import "./globals.css";
import LanguageSelector from "@/components/custom-ui/LanguageSelector";
import Logo from "@/components/custom-ui/Logo";

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-orbitron",
});

const aptos = localFont({
  src: [
    {
      path: '../../public/fonts/Aptos.ttf',
      weight: '400',
      style: 'normal',

    },
  ],
  variable: "--font-aptos",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${aptos.variable} ${orbitron.variable} antialiased`}
      >
        <Logo />
        <LanguageSelector />
        <PrimaryNav />
        {children}
      </body>
    </html>
  );
}
